global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  resolution: 0.2
  rolling_window:             false
  track_unknown_space:        true
  width:                      128.0
  height:                     128.0
  origin_x:                   -64.0
  origin_y:                   -64.0

  plugins:
     - {name: obstacles_costmap2d2,       type: "costmap_2d::ObstacleLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
